### ISSUE TITLE
chapter11a.scala answer4 issue

### ISSUE THREAD

**Issue by mamaorha** [marcus-nl/scala-impatient-2nd-ed#1]
overriding the "<" with wrong method
Amount(3, 1) < Amount(2, 14) is returning "True" but it should be "False"

+ btw Should probably use the GCD after the calculations to normalize the fraction

**Comment by marcus-nl** [comment]
Thanks mamaorha, I only saw this issue just now. Amount.< should be correct now.

Regarding normalization with gcd, I don't think that applies to Amount, since it represents a decimal value, not a fraction.
